# Generated by Django 4.0.5 on 2022-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
