# Generated by Django 4.0.5 on 2022-06-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.project'),
        ),
    ]
